### PR TITLE
LPS-88743

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ricky-pan @spencerwoo

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:staging

**Comment by SpencerWoo** [comment]
https://github.com/jonathanmccann/liferay-portal/pull/1782
> https://issues.liferay.com/browse/LPS-88743
tests: SpencerWoo#47 (comment)
I commented SpencerWoo#47 (comment) but @ricky-pan talked to Angelo and they wanted to forward this.

>> See conversation here: SpencerWoo/liferay-portal-ee#68
 Bug cannot be fully reproduced on master because of https://issues.liferay.com/browse/LPS-90401. However, based on the logic of the code, the issue present in 7.1 should then become reproducible after fixing LPS-90401.

**Comment by Alec-Shay** [comment]
Thanks guys. I've taken a quick look at this, though I want to check it a bit further. I should be able to get to that early tomorrow.

**Comment by Alec-Shay** [comment]
@ricky-pan I just have one thing I'm not sure about before I push forward to Tamás -- specifically [this commit](https://github.com/Alec-Shay/liferay-portal/pull/26/commits/9827ca8b24de3aa547a2a38a7a77f5fff80164e9). So to be clear -- because the content has not yet been imported from the first iteration, this means the links are not properly updated, and that is the only thing that needs to be corrected on the second iteration?

My concern is I feel adding it like this may significantly impact performance for large web content imports since now it'll always do everything twice. A lot of clients end up just mass exporting/importing everything at once sooner or later and doubling the web content imports would exacerbate performance issues that are sometimes already a concern. I wonder if we could keep track of which web contents need to have their links corrected with a flag of some sort, and then just do that part for the articles that need it?

I can also just push this to Tamás and bring this up to him to see if he has the same concern. Let me know what you think though if you can. Thanks.

**Comment by ricky-pan** [comment]
I agree; the second iteration of the search should be done only if necessary. The difficulty is what you have mentioned - creating a flag to track whether an article's references are correctly imported. As I understand it, the fetching of articles from the database happens in the `JournalArticleExportImportContentProcessor.java` class [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/exportimport/content/processor/JournalArticleExportImportContentProcessor.java#L392-L394). I've considered ways of adding a flag, but I haven't come to a solution that doesn't add attributes or methods that refer to the objects themselves. I tried to keep away from doing this, but I think this would ultimately be beneficial especially in the use-cases you mention. What do you think?

**Comment by Alec-Shay** [comment]
@ricky-pan What about adding a map as a parameter to the parameterMap to the [portletDataContext](https://github.com/Alec-Shay/liferay-portal/pull/26/commits/9827ca8b24de3aa547a2a38a7a77f5fff80164e9#diff-edb5361b9bdffa021c6d8f872ec59b1bR404)? It's passed into the JournalArticleStagedModelDataHandler and then all the way to the [JournalArticleExportImportContentProcessor](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/exportimport/data/handler/JournalArticleStagedModelDataHandler.java#L580), so maybe if any article import is not able to correct its link on the first iteration, we can add the article's ID to the map and check which ones need to be corrected at the end. Is that something you already considered?

**Pull request closed without merging**
