### PR TITLE
LPS-71490

### PR DESCRIPTION
**Pull request by danielkocsis**
Hey @Alec-Shay,

could you please test it with your scenarios? If it work please forward it to Brian, if not, please let me know!

thanks,
Daniel

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:reopen

**Comment by danielkocsis** [comment]
ci:retest

**Comment by Alec-Shay** [comment]
Hello @danielkocsis,

I've tested it with the use case for LPS-71490, and unfortunately it doesn't seem to be working for our use case (or even just a base-case Remote Staging publish).

The following ClassNotFoundException gets thrown from [this method call](https://github.com/Alec-Shay/liferay-portal/pull/7/commits/11de776258cbacd9e0e3db898ec625d23c088481#diff-5ef7b61aefcb4fe30459464d73c49196R132) of `TunnelUtil.invoke()` in `StagingServiceHttp.propagateExportImportLifecycleEvent()`: https://gist.github.com/Alec-Shay/377195f6ed214f26b201ec169fe4813f

It seems to happen for any event it tries to propagate, whether it's a "STARTED" event, "SUCCEEDED" event, etc. As such, nothing gets registered on the live site's side, and the behavior is unchanged, except for this error.

I'm not 100% sure why this happens -- but could it possibly have to do with the fact that `StagingServiceHttp` and `StagingServiceImpl` are in portal-impl, whereas ExportImportLifecycleEventImpl is in a module?

As for the test failure in this PR, it was definitely caused by these changes, but I'm rerunning the tests again now, and I think the last commit you added might fix it. Looks good so far, except for that error.

**Comment by danielkocsis** [comment]
Hey @Alec-Shay,

yes, I realized the issue, so added the last one to fix it. We have a public holiday in Hungary tomorrow and next Monday, but please feel free to send me your results.

thanks,
Daniel

**Comment by Alec-Shay** [comment]
@danielkocsis I have the results of the test (I ran it a couple times because tests were failing in upstream), and I'm pretty sure the last commit fixed the test failure.

However, I'm still trying to figure out what to do to fix the ClassNotFoundException in `StagingServiceHttp.propagateExportImportLifecycleEvent()`, so the fix can work.

**Comment by Alec-Shay** [comment]
@danielkocsis We've looked at this, and for whatever reason the TunnelServlet class just can't find `ExportImportLifecycleEventImpl`. We think either it's because that class is in a module (so it might not be visible from portal-impl), or because there is a bug with the ClassLoader in TunnelServlet.

I know you will be on holiday, but once you are back, could you take a look at the fix and try to get it working? Thanks!

**Comment by danielkocsis** [comment]
hey @Alec-Shay,

i've talked with platform team and it is a known limitation of the TunnelServlet/Util pair, what is responsible for remote method calls in staging today. So I am working on to find a solution that doesn't cause class loading issues.

As soon as I am ready I'll resend this change!

Daniel

**Comment by Alec-Shay** [comment]
Okay -- thanks for looking more into it, @danielkocsis.

**Comment by danielkocsis** [comment]
Hey @Alec-Shay,

I pushed up some changes and locally it looks OK to me. Could you please re-try to test it?

thanks,
Daniel

**Comment by Alec-Shay** [comment]
@danielkocsis I've tested it again now. It avoids the TunnelServlet class loading issues now, but still isn't working. Have you tested this?

I debugged it again, and it seems like some of the fired events are being picked up on the remote side, but when it registers the callback using the [ExportImportProcessCallbackUtil static method here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/export-import/export-import-service/src/main/java/com/liferay/exportimport/lar/ExportImportProcessCallbackUtil.java#L46), the stack is still empty. I think either there needs to be another special case in `DefaultProcessAwareExportImportLifecycleListener` that calls the methods there (onProcessStarted(), onProcessSucceeded(), and onProcessFailed()), or there's another type of event that would need to be propagated for it to work.

**Comment by danielkocsis** [comment]
hey @Alec-Shay,

I did not have time to test it, I just finished it before I left the office, but wanted to know whether it works or not by the start of my day today. Unfortunately the answer is No :( 

So I did a lot of debug, and I realized the whole framework (which is really similar to the transaction callback one) can't handle multi threaded environment. So the next step is to make it work with multiple threads :S 

I am closing this pull now, and resend you a new one once it is ready.

thanks,
Daniel

**Comment by Alec-Shay** [comment]
Sorry to hear that, @danielkocsis. I didn't realize the problem was with the whole framework.

I'll look out for the new pull when it's ready -- and in the meantime just let me know if there's anything I can help with.

Thanks.

**Comment by danielkocsis** [comment]
@Alec-Shay,

I am pretty sure this solution won't be backportable :) so If you could work on your original solution to be able to commit that to 7.0.x, that would be a great help, and I would really appreciate this, of course only if you have free resources for that! So my biggest problem with that was, that we are able to configure remote staging locally and in this case we would need to be able to detect this scenario, because in this case we mustn't duplicate the events. So if you could resolve this scenario, then I guess your solution can be an alternative for 7.0.x. It won't be that flexible, but for this exact issue, I think it could work.

What do you think?

Daniel

**Comment by Alec-Shay** [comment]
@danielkocsis,

Thank you for letting me know that up-front.

However, I'm not sure I understand exactly why we cannot duplicate the events. Even if the remote staging is configured locally, I'm not entirely sure why it's a problem, per se. Can the events interfere with each other somehow if they're in the same JVM? Or is it just too redundant?

If I understand correctly, you're saying that the remote (live) site, when done locally, should be able to detect this and use the same events that the Staging site is firing, right? So, basically allow those events to work for the purpose of callbacks, but only if it's using "local" remote staging? There are a lot of implementation details I'd still need to figure out for that, but if that's what you mean, I suppose it should be doable.

**Comment by danielkocsis** [comment]
@Alec-Shay,

my problem is the redundancy. So I can imagine long running events and if no one ever checks if we duplicate events or not, we can trigger to run the same event 2 times easily. And of course nothing prevents you to write such a logic that can be harmful if you run it twice. 

Regarding the solution, my approach was to not fire (duplicate) the events, once I detect it is staged locally. But I can imagine other solutions as well.

**Comment by Alec-Shay** [comment]
@danielkocsis I think maybe I was thinking of the wrong examples of "local" remote staging. Somehow I was still confusing it with the case of configuring remote staging with two instances on the same machine (I mistakenly thought it wouldn't let you configure remote staging with two sites in the same instance).

Anyway, I'll work on implementing that as a backportable solution, and let you know (probably send a PR) when I've made progress. Thanks.

**Comment by Alec-Shay** [comment]
@danielkocsis Wait -- actually, sorry, I'm still not sure about this.

Working with it a bit more, it seems like the `ExportImportProcessCallbackLifecycleListener` is local to a specific group; thus, even when I test with Remote staging locally (same JVM), they have separate callback stacks, so without firing more events duplicating the ones on the Staging site, it still couldn't register new ones properly. I tested this myself by debugging the use case on our ticket -- using links to pages, even "local" remote Staging still has this issue, implying it still needs to fire the events on the live side.

So I'm struggling to see how this would work without duplicating the originally fired events on the Staging site, for the other stack for the live site. Maybe I'm missing something?

**Comment by danielkocsis** [comment]
Hey @Alec-Shay,

so, it works like this:

- when you send a "process-started" event, the framework automatically pushes a new empty list to a queue
- when you send a "process-finished" event, the framework pop's the latest element from the queue, and try to get all the items from that list, and process those items (those are your callbacks)
- when you invoke `ExportImportProcessCallbackRegistryUtil.registerCallback(Callable c)`
the framework adds this callable as a new item to the list which is in the top of the queue in that moment


So what happens when you do remote staging?

- `LayoutStagingBackgroundTaskExecutor` controls the whole process

1. it send a "process-started" event (new list is being pushed to the que)
2. during the export you register a few callbacks (it goes to that List we created before)
3. export finished
4. import started on the Live side, (either on the same JVM, or on another JVM, machine, vm, etc...)
5. if you send another process started at this  point
 - if you are on the same JVM: a new list is being pushed to the stack, so all the callback registered from this point will go to this new list, or it will be empty!
- if you are on a separate JVM: it will create a new queue, and pushes a new empty list to it (should we synchronize the callback stack??)
6. You send a "process finished" signal, at the end of the import -> it fetches the top list from the queue, probably this is going to be empty, or contains the callbacks registered since the previous "process-started" signal
7. you send another "process finished" signal at the end of the whole process, from the 
`LayoutStagingBackgroundTaskExecutor` (which runs on the JVM of the stage environment) it pops the top element from the queue again, and invokes all the registered callback from the list

So as you can see all the "start" signal triggers to open a new List where the callback will be registered, and all the "end" signals triggers to run the registered callbacks from the top of the queue.

**Comment by Alec-Shay** [comment]
Hey @danielkocsis,

Yes, that's something like what I've seen in debugging in local Staging. The problem I'm seeing is, no matter whether it's on the same JVM or not (done locally or not), I'm not seeing just one callback stack.

Hopefully it's not an eyesore, but to prove what I'm seeing, here is the process I trace when debugging with locally configured remote Staging (or non-locally configured remote Staging, for that matter):

- The Staging/export side begins its export, and fires the event code 18 (`EVENT_PUBLICATION_LAYOUT_REMOTE_STARTED`). This causes it to push to the callback stack, setting it up for callbacks to be registered later.

1 - stagingsite push

- As it's exporting things (portlets and layouts), it successfully registers many callbacks -- most of them are to "update last publish date" (which makes sense, since it's exporting)

2 - stagingsite successfulregister

- At some point, the remote/live side finally begins its import of the layouts...

3 - livesite beginlayoutsimport

- It starts trying to register callbacks, but it fails -- nothing is pushed to the stack! The export/Staging side still hasn't popped the "update last publish date" callbacks, so that stack shouldn't be empty -- which implies there is a different stack being used for the import/live side. And thus, registration of the callbacks fails, and they are called immediately instead.

4 - livesite callbackregisterattempt

- The same thing happens with the ImportLinkedLayoutCallable (the most important one for our specific use case). The stack is always empty, so it's just called immediately.

5 - livesite registerimportlinkedlayoutcallable
6 - livesite registerimportlinkedlayoutcallable

- Finally, when everything's finished importing, the Staging/export side fires the `EVENT_PUBLICATION_LAYOUT_REMOTE_SUCCEEDED` event, which causes it to pop the stack on its side. This shows us more proof that those "update last publish date" callbacks didn't just vanish, but were in a different stack this whole time:

7 - stagingsite stackpop



... So my problem is that, to me, it seems like we need to fire more events on the import/live side, even if it's on the same JVM. If we skip this for locally configured remote Staging, then it will stay broken for this use case, because it seems to work the same either way. Unless we can actually synchronize the stacks somehow like you mentioned? Although I'm not sure how that would be done in a way that's backportable.

**Pull request closed without merging**
