### PR TITLE
[TECHNICAL-SUPPORT] LPS-94690

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @knchau

Notes from Kim:
> https://issues.liferay.com/browse/LPS-94690
> 
> The issue is when the site is staging. At every page load of the Control Panel, the local server would send a request to the remote server. This can cause the site to hang because the request is sent in https://github.com/SamZiemer/liferay-portal/commit/066cdaddcb673cb86fa7b8c0d124bc94cb730392#diff-2db79331dcd02f15d22749213538877fL46. The timeout can take 30 seconds.
> 
> My changes move the logic to the backend in a thread using the quartz scheduler. The quartz scheduler monitors the remote server's connection and updates the remote display URL. 
> 
> https://github.com/SamZiemer/liferay-portal/commit/180e3c4977dd28f4c27ca94ff4e61eef95e806db initially caches the remote URL when remote staging is enabled. 
> 
> https://github.com/SamZiemer/liferay-portal/commit/8ceb788b52d9bf3f609318ab36613cacf750b317#diff-9bf2f5518a6bd236e54fde2bb44520c4R119 monitors the connection and updates the cached remote URL. This value will be updated into typeSettingsProperties. If there is an error, it will not cause the site to hang instead it will throw an error. 
> 
> The updated/cached display URL is referenced in the jsp instead of pinging the remote server to populate the href.
> 
> https://github.com/SamZiemer/liferay-portal/commit/efb194a517f9346b90c17e164b2c173974b25f22 stores data into Message so it can be referenced in StageMessageListener.java. It will update the group's value at every page load of the Control Panel.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by Alec-Shay** [comment]
Hey @knchau,

I know this issue has to do with getting the live URL, right?

Do you think the test failures (in the comment above this) may be related to changes here?

**Comment by Alec-Shay** [comment]
@knchau  If you have any questions about checking up on that, of course feel free to reach out, as well. Just let me know if so

**Comment by knchau** [comment]
@Alec-Shay, thank you for pointing that out, I didn't see those last errors. 

Upon reviewing the test class, it looks like it's due to the test class not having a theme display in their service context. I'm thinking that I can place a check if any of the values are null before calling the GroupServiceHttp.getGroupDisplayURL(), like so:

	String groupDisplayURL;

	if (serviceContext != null &&
		serviceContext.getThemeDisplay() != null) {

		ThemeDisplay themeDisplay = serviceContext.getThemeDisplay();

		Layout layout = themeDisplay.getLayout();

		boolean privateLayout = layout.isPrivateLayout();

		groupDisplayURL = GroupServiceHttp.getGroupDisplayURL(
			httpPrincipal, remoteGroupId, privateLayout, secureConnection);
	}

Do you think this would be an appropriate fix? -- I have rerun the gradle tests and it passes.

**Comment by Alec-Shay** [comment]
@knchau Yeah, that makes sense to me.

Do you think you would be able to push that as a new commit and send it to me? I've looked over the commits themselves and I think I can push it forward to Tamas with that. I'd much appreciate it -- thanks!

**Comment by knchau** [comment]
@Alec-Shay Can do, I'll send that over to you https://github.com/Alec-Shay/liferay-portal/pull/42

**Comment by Alec-Shay** [comment]
Sent to Tamas: https://github.com/moltam89/liferay-portal/pull/502

**Pull request closed without merging**
