### PR TITLE
LPS-89294 NoConnectionException if live server is down when switching tabs

### PR DESCRIPTION
**Pull request by knchau**
Hey @Alec-Shay, 

I have specified the changes to take effect on the two methods that printed the error logs. 

The fix was to throw an exception when switching between tabs, resulting in a UI display that there is no connection to the remote server. The error log is swallowed from the change to the service_http template. 

https://issues.liferay.com/browse/LPS-89294

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by Alec-Shay** [comment]
@knchau  Thanks. Sent to Tamas here: https://github.com/moltam89/liferay-portal/pull/481

Note I also changed: https://github.com/moltam89/liferay-portal/pull/481/commits/5d5a465e678928a12690b3ea9434a452da643890

**Comment by Alec-Shay** [comment]
I noticed after I'd sent that a couple of the commit messages had a typo in them for the LPS number... I reworded them and resent it again: https://github.com/moltam89/liferay-portal/pull/482

**Pull request closed without merging**
