### PR TITLE
LPS-89294 NoConnectionException if live server is down when switching tabs in Publishing > Staging

### PR DESCRIPTION
**Pull request by knchau**
I've made changes that Tamás suggested, removing the changes done to GroupServiceHttp.
https://github.com/moltam89/liferay-portal/pull/477#issuecomment-469324495

https://issues.liferay.com/browse/LPS-89294
https://issues.liferay.com/browse/LPP-32794

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by Alec-Shay** [comment]
Hello @knchau,

My understanding is that the difference between this and your last PR (https://github.com/Alec-Shay/liferay-portal/pull/24) is the removal of [this code change](https://github.com/moltam89/liferay-portal/pull/477/commits/4dd157578c214ad03f3b7bdc2e2176b168ab595c#diff-bd23eebd42c70ad9360319500cbf679eR27) -- but looking at the LPS, is that not still a change we want to address the issue?

I was under the impression that moltam89#477 (comment) meant we should not modify `GroupServiceHttp` because it is a generated class, though he didn't comment necessarily on the change.

If we really need this change, it is something we could still add, though it would have to be generated, after the change is made to the template: https://github.com/liferay/liferay-portal/blob/master/modules/util/portal-tools-service-builder/src/main/resources/com/liferay/portal/tools/service/builder/dependencies/service_http.ftl#L138 (maybe it would have to be a special exception for GroupServiceHttp specifically? Since this file is used to generate several different *ServiceHttp files)

**Comment by knchau** [comment]
Hi @Alec-Shay,

I misinterpreted [moltam89#477](https://github.com/moltam89/liferay-portal/pull/477). 

The LPS does ask for that change of swallowing the console log error, but because I misinterpreted the comment and there was a similar occurrence (which a banner was already implemented but it would still print the console log error) in the staging page when you try to create a new process while the live server is down. 

I assumed that it would be okay to mimic its behavior. I am unsure if we should change the template since there was a similar behavior. Do you think the change in the template should be made?

**Comment by Alec-Shay** [comment]
@knchau Hmm... That I'm not sure of. From my understanding of the LPS, it seems like that is essentially the point of what it refers to as a bug, although I am not sure myself whether I would say the similar existing behavior justifies it or not (you could argue it is a bug because of the way it happens, in this case, though I could also see an argument for it being the accepted precedent). If you want to push that change (since it seems to have been your initial goal) to the template, maybe you could add that as a new commit and we could push it to Tamás again and see what he thinks?

**Comment by knchau** [comment]
@Alec-Shay Yeah, that sounds good. I'll do that, but I will have to talk with Greg since I am not sure how the change should be made on the template.

**Comment by knchau** [comment]
I updated the template and included the changed file, but not sure if I should have included the updated auto-generated file. If that is not needed, I can update the commit.

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by Alec-Shay** [comment]
@knchau Is it also intentional that the change is made to all of those various methods, as opposed to just the couple of methods you had changed originally ([here](https://github.com/moltam89/liferay-portal/pull/477/commits/4dd157578c214ad03f3b7bdc2e2176b168ab595c#diff-bd23eebd42c70ad9360319500cbf679eL201) and [here](https://github.com/moltam89/liferay-portal/pull/477/commits/4dd157578c214ad03f3b7bdc2e2176b168ab595c#diff-bd23eebd42c70ad9360319500cbf679eR405))? Generally we avoid swallowing Exceptions as much as possible to prevent making potential issues down the line harder to track down, so I have a feeling we may want to make the logic in the template even more specific to those methods.

Also, would it be alright with you to separate out the generated changes into a separate commit (ideally including the command you used to generate it)? I believe that is our preferred approach to committing generated changes.

**Comment by knchau** [comment]
@Alec-Shay Ah I see, I'll make the changes specified to those methods and I'll separate the generated changes into a separate commit.

**Comment by Alec-Shay** [comment]
@knchau Sounds good to me. I'll go ahead and close this PR for now, so you can send me a new one when you have that. Feel free to ask if you have more questions, too. Thanks!

**Pull request closed without merging**
