### PR TITLE
LPS-102383 Document change-tracking-spi

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Alec-Shay** [comment]
Hello @Preston-Crary,

Sorry for the long delay in getting back to you on this. We'd like to move this forward now, although there's 

Per our [Javadoc guidelines](https://github.com/liferay/liferay-portal/blob/master/readme/JAVADOC_GUIDELINES.markdown#method-comments), method comments are required for each interface, and they must also each have descriptions for each parameter and return type. Some of them might be trivial, but just so as to avoid any inaccuracies, I'd rather it be someone familiar with the interfaces who writes them before we review them if possible.

Could I ask you to complete these parts of the Javadocs, so we can also review and include those before pushing them up? It would be much appreciated. Thanks!

**Comment by Preston-Crary** [comment]
Pushed changes to add the parts you asked for and rebase the pull.

**Comment by Alec-Shay** [comment]
ci:forward

**Comment by Alec-Shay** [comment]
ci:stop

**Comment by Alec-Shay** [comment]
ci:stop

**Comment by Alec-Shay** [comment]
@Preston-Crary Thank you. Please see: https://github.com/brianchandotcom/liferay-portal/pull/94227

**Pull request closed without merging**
