### PR TITLE
J cords wcm 1425

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/WCM-1425
https://issues.liferay.com/browse/LPP-33306

Problem: UserGroup's DataModelStagedHandler doesn't have doImportMissingReference() implemented, so when Audience Targeting tries to import a User Segment based on a User Group it fails.

Solution: Implement the doImportMissingReference() method.

Note: The only way I have found to test this is on 7.1.x using Audience Targeting according to the instructions in WCM-1425. I could see needing a PTR to clarify if this implementation takes enough factors into account.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by Alec-Shay** [comment]
Thanks, @joshuacords. I don't see anything wrong with this myself, so I'll go ahead and push this to Tamás in just a minute.

**Comment by Alec-Shay** [comment]
Closed for rebasing as per our discussion: https://github.com/Alec-Shay/liferay-portal/pull/29

**Pull request closed without merging**
