### PR TITLE
LPS-63852

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by blzaugg** [comment]
@Alec-Shay, can you test this?

**Comment by Alec-Shay** [comment]
I've tested this on both master and 6.2.10 SP13, and it seems to work properly as far as resolving the issue with search results not appearing in the popup after typing in the search field, with or without following with a nav-key.

However, I'm noticing another issue with this fix, which is that the search results that are shown when something is typed in do not have any effect when their checkboxes are selected. The categories should be added to a list in the configuration menu where they'll be used to filter assets shown, but with the fix, only the categories shown with no search can be used to actually add to or remove from that list.

On a related note, the same categories that are shown in the tree structure with no search query do not update or get updated by the same categories shown after a search, so their states do not match each other after one is changed; i.e., if you check the checkbox for a category when the popup first appears and then search for it, it'll come up as unchecked. This seems to happen both before and after the fix.

In my testing though it seems that the issue with the categories being selected after the search is only present after the fix. I haven't tested whether previous fixes caused the same regression.

**Comment by blzaugg** [comment]
I'll need to do more testing than. Thanks

**Comment by blzaugg** [comment]
I think I know the issue

**Comment by Alec-Shay** [comment]
This part of the end of _initSearch() happening too soon maybe?

```
if (instance.get('singleSelect')) {
                                var onSelectChange = A.bind('_onSelectChange', instance);

                                popup.entriesNode.delegate('change', onSelectChange, 'input[type=radio]');
                            }
```

**Comment by blzaugg** [comment]
I think it's the placeAfter() and the searchResults not being added to a TreeNode.

Go ahead and formally Escalate this to me. I'm going to have to take a more in-depth look at it.

**Comment by Alec-Shay** [comment]
Okay. I'll have them close the pull request currently in review for the LPS because it looks like more still needs to be done.

**Pull request merged**
