### PR TITLE
LPS-93204

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-93204

Hello  @Alec-Shay ,

The issue here is that:
> Importing web content to a new environment creates a duplicate default structure if the structure was "edited" in the initial environment.

The PTR associated with LPS-93204 has concluded that the behavior is not intended and should fixed in such a way so that:
> About the export/import related issue:
> If I understand it correctly, the problem is that the default Web Content Structure is not considered as "preloaded", because it was edited.
> This seems wrong to me, we should check the first version's userId as we do it for Web Contents, and consider the default structure "preloaded".

The fix checks whether the default web content structure and web content template have been edited. If they have been edited, their ids will be used to fetch the original versions of the two and use the userId of the original versions to be compared with the defaultUserId.

Please let me know if you have any questions. Thanks.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by Alec-Shay** [comment]
Hi @brianikim,

Sorry for the delay in getting to this. It looks good to me, so I'll go ahead and send it to Tamás to take a look at in a minute. Thanks!

**Comment by Alec-Shay** [comment]
Sent to: https://github.com/moltam89/liferay-portal/pull/491

**Comment by brianikim** [comment]
Hey @Alec-Shay ,

No worries. Thank you for taking care of the review :D

Sincerely,
Brian Kim

**Pull request closed without merging**
